library(tidyverse)
library(tibble)
library(sf)
library(janitor)
calles <- st_read("C:/Users/Santi/Desktop/Santi/Ciencia de Datos/Instrumento de Analisis Urbano II/R/Ejercicios/Datasets/Zarate/Shapes/Ejes_882.shp")
Ejes <- as_tibble(Ejes)
ggplot() + geom_sf(data = calles)
hitos <- st_read("C:/Users/Santi/Desktop/Santi/Ciencia de Datos/Instrumento de Analisis Urbano II/R/Ejercicios/Datasets/Zarate/Shapes/Hitos_882.shp")
ggplot() + geom_sf(data = hitos)
poligono <- st_read("C:/Users/Santi/Desktop/Santi/Ciencia de Datos/Instrumento de Analisis Urbano II/R/Ejercicios/Datasets/Zarate/Shapes/Polyg_882.shp")
ggplot() + geom_sf(data = poligono)
poligono <- filter(poligono, CODLOC=="040")
radios <- st_read("C:/Users/Santi/Desktop/Santi/Ciencia de Datos/Instrumento de Analisis Urbano II/R/Ejercicios/Datasets/Zarate/Shapes/Rad_882.shp")
ggplot() + geom_sf(data = radios)
radios <- filter(radios, COD_LOC=="040")
ggplot() + geom_sf(data = radios, aes(fill=TIPO))
hitos <- st_transform(hitos, crs= st_crs(radios))
hitos <- st_intersection(hitos, radios)              
ggplot() + geom_sf(data = radios, aes(fill=TIPO)) + geom_sf(data=hitos)
