library(tidyverse)
library(tibble)
library(sf)
library(janitor)
calles <- st_read("C:/Users/Santi/Desktop/Santi/Ciencia de Datos/Instrumento de Analisis Urbano II/R/Ejercicios/Datasets/Zarate/Shapes/Ejes_882.shp")
ggplot() + geom_sf(data = calles)
hitos <- st_read("C:/Users/Santi/Desktop/Santi/Ciencia de Datos/Instrumento de Analisis Urbano II/R/Ejercicios/Datasets/Zarate/Shapes/Hitos_882.shp")
ggplot() + geom_sf(data = hitos)
poligono <- st_read("C:/Users/Santi/Desktop/Santi/Ciencia de Datos/Instrumento de Analisis Urbano II/R/Ejercicios/Datasets/Zarate/Shapes/Polyg_882.shp")
ggplot() + geom_sf(data = poligono)
poligono <- filter(poligono, CODLOC=="040")
radios <- st_read("C:/Users/Santi/Desktop/Santi/Ciencia de Datos/Instrumento de Analisis Urbano II/R/Ejercicios/Datasets/Zarate/Shapes/Rad_882.shp")
ggplot() + geom_sf(data = radios)
radios <- filter(radios, COD_LOC=="040")
ggplot() + geom_sf(data = radios)
hitos <- st_transform(hitos, crs= st_crs(radios))
hitos <- st_intersection(hitos, radios)              
ggplot() + geom_sf(data = radios, aes(fill=TIPO)) + geom_sf(data=hitos)
PBA <- st_read("C:/Users/Santi/Desktop/Santi/Ciencia de Datos/Instrumento de Analisis Urbano II/R/Ejercicios/Datasets/PBA/Buenos_Aires_con_datos.shp")
LOC <- st_read("C:/Users/Santi/Desktop/Santi/Ciencia de Datos/Instrumento de Analisis Urbano II/R/Ejercicios/Datasets/Localidades Censales/pxlocdatos.shp")
LOC <- filter(LOC, departamen=="Zárate")
PBA <- filter(PBA, link %in% c("068820501", "068820502", "068820503", "068820504", "068820505", "068820506", "068820507"))
PBA <- st_transform(PBA, crs = st_crs(radios))
PBA <- st_intersection(PBA, radios)
ggplot()+geom_sf(data = radios, aes(fill=TIPO)) + geom_sf(data = PBA, fill=NA, color="red", size=3)
unique(PBA$geometry)
RC <- PBA %>% group_by(link) %>% summarise(varon=sum(varon),
                                           mujer=sum(mujer),
                                           totalpobl=sum(totalpobl),
                                           hogares=sum(hogares),
                                           viviendasp=sum(viviendasp),
                                           viv_part_h=sum(viv_part_h))
as_tibble(PBA)
ggplot()+ geom_sf(data = RC, aes(fill=totalpobl)) + scale_fill_viridis_c()
ggplot()+ geom_sf(data = PBA, aes(fill=totalpobl)) + scale_fill_viridis_c()
